# -----------
# Constantes
# -----------


GRAVEDAD = 9.8
RELACION_PIXELS = 100 #CADA PIXEL ES 1cm POR LO QUE TENGO QUE DIVIDIR POR ESTE FACTOR

BRAZO_PENDULO = 200

MASA_PENDULO = 10
MASA_CARRO = 100